export default class Day {
    static propTypes: {
        ariaLabelPrefixWhenEnabled: any;
        ariaLabelPrefixWhenDisabled: any;
        disabledKeyboardNavigation: any;
        day: any;
        dayClassName: any;
        endDate: any;
        highlightDates: any;
        inline: any;
        shouldFocusDayInline: any;
        month: any;
        onClick: any;
        onMouseEnter: any;
        preSelection: any;
        selected: any;
        selectingDate: any;
        selectsEnd: any;
        selectsStart: any;
        selectsRange: any;
        startDate: any;
        renderDayContents: any;
        handleOnKeyDown: any;
        containerRef: any;
        monthShowsDuplicateDaysEnd: any;
        monthShowsDuplicateDaysStart: any;
        locale: any;
    };
    componentDidMount(): void;
    componentDidUpdate(prevProps: any): void;
    dayEl: any;
    handleClick: (event: any) => void;
    handleMouseEnter: (event: any) => void;
    handleOnKeyDown: (event: any) => void;
    isSameDay: (other: any) => any;
    isKeyboardSelected: () => any;
    isDisabled: () => any;
    isExcluded: () => any;
    getHighLightedClass: (defaultClassName: any) => any;
    isInRange: () => any;
    isInSelectingRange: () => any;
    isSelectingRangeStart: () => any;
    isSelectingRangeEnd: () => any;
    isRangeStart: () => any;
    isRangeEnd: () => any;
    isWeekend: () => boolean;
    isOutsideMonth: () => boolean;
    getClassNames: (date: any) => any;
    getAriaLabel: () => string;
    getTabIndex: (selected: any, preSelection: any) => 0 | -1;
    handleFocusDay: (prevProps?: {}) => void;
    renderDayContents: () => any;
    render: () => any;
}
