export default class Month {
    static propTypes: {
        ariaLabelPrefix: any;
        chooseDayAriaLabelPrefix: any;
        disabledDayAriaLabelPrefix: any;
        disabledKeyboardNavigation: any;
        day: any;
        dayClassName: any;
        monthClassName: any;
        endDate: any;
        orderInDisplay: any;
        excludeDates: any;
        filterDate: any;
        fixedHeight: any;
        formatWeekNumber: any;
        highlightDates: any;
        includeDates: any;
        inline: any;
        shouldFocusDayInline: any;
        locale: any;
        maxDate: any;
        minDate: any;
        onDayClick: any;
        onDayMouseEnter: any;
        onMouseLeave: any;
        onWeekSelect: any;
        peekNextMonth: any;
        preSelection: any;
        setPreSelection: any;
        selected: any;
        selectingDate: any;
        calendarStartDay: any;
        selectsEnd: any;
        selectsStart: any;
        selectsRange: any;
        showWeekNumbers: any;
        startDate: any;
        setOpen: any;
        shouldCloseOnSelect: any;
        renderDayContents: any;
        showMonthYearPicker: any;
        showFullMonthYearPicker: any;
        showTwoColumnMonthYearPicker: any;
        showFourColumnMonthYearPicker: any;
        showQuarterYearPicker: any;
        handleOnKeyDown: any;
        isInputFocused: any;
        weekAriaLabelPrefix: any;
        containerRef: any;
        monthShowsDuplicateDaysEnd: any;
        monthShowsDuplicateDaysStart: any;
    };
    MONTH_REFS: any[];
    isDisabled: (date: any) => any;
    isExcluded: (date: any) => any;
    handleDayClick: (day: any, event: any) => void;
    handleDayMouseEnter: (day: any) => void;
    handleMouseLeave: () => void;
    isRangeStartMonth: (m: any) => any;
    isRangeStartQuarter: (q: any) => any;
    isRangeEndMonth: (m: any) => any;
    isRangeEndQuarter: (q: any) => any;
    isWeekInMonth: (startOfWeek: any) => any;
    renderWeeks: () => any[];
    onMonthClick: (e: any, m: any) => void;
    handleMonthNavigation: (newMonth: any, newDate: any) => void;
    onMonthKeyDown: (event: any, month: any) => void;
    onQuarterClick: (e: any, q: any) => void;
    getMonthClassNames: (m: any) => any;
    getTabIndex: (m: any) => "0" | "-1";
    getAriaLabel: (month: any) => string;
    getQuarterClassNames: (q: any) => any;
    renderMonths: () => any[];
    renderQuarters: () => any;
    getClassNames: () => any;
    render(): any;
}
